### ISSUE TITLE
Infinite loop in starting tuxguitar-windows-x86

### ISSUE THREAD

**Issue by pterodactylus42** [pterodactylus42/tuxguitar#1]
After building tuxguitar-2.0-SNAPSHOT for windows-x86 I ran tuxguitar.bat from the target folder. The ui opens, but is not responsive and gets into an infinite loop.
Stacktrace:
java.lang.NullPointerException at org.herac.tuxguitar.song.managers.TGSongManager.getVisibleTracks(TGSongManager.java:1060) at org.herac.tuxguitar.app.view.component.tab.Tablature.getTrackSelection(Tablature.java:241) at org.herac.tuxguitar.graphics.control.TGLayoutVertical.paintSong(TGLayoutVertical.java:46) at org.herac.tuxguitar.graphics.control.TGLayout.paint(TGLayout.java:162) at org.herac.tuxguitar.app.view.component.tab.Tablature.paintTablature(Tablature.java:81) at org.herac.tuxguitar.app.view.component.tab.TGControl.paintTablature(TGControl.java:121) at org.herac.tuxguitar.app.view.component.tab.TGControlPaintListener.paintControl(TGControlPaintListener.java:16) at org.herac.tuxguitar.app.view.util.TGBufferedPainterLocked.fillPaintBuffer(TGBufferedPainterLocked.java:52) at org.herac.tuxguitar.app.view.util.TGBufferedPainterLocked.paintBufferLocked(TGBufferedPainterLocked.java:61) at org.herac.tuxguitar.app.view.util.TGBufferedPainterListenerLocked.onPaint(TGBufferedPainterListenerLocked.java:14) at org.herac.tuxguitar.ui.event.UIPaintListenerManager.onPaint(UIPaintListenerManager.java:33) at org.herac.tuxguitar.ui.swt.event.SWTPaintListenerManager.paintControl(SWTPaintListenerManager.java:20) at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066) at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1563) at org.eclipse.swt.widgets.Control.windowProc(Control.java:4818) at org.eclipse.swt.widgets.Display.windowProc(Display.java:4820) at org.eclipse.swt.internal.win32.OS.UpdateWindow(Native Method) at org.eclipse.swt.widgets.Decorations.setVisible(Decorations.java:1312) at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:1958) at org.eclipse.swt.widgets.Shell.open(Shell.java:1267) at org.herac.tuxguitar.ui.swt.widget.SWTWindow.open(SWTWindow.java:70) at org.herac.tuxguitar.app.view.main.TGWindow.open(TGWindow.java:51) at org.herac.tuxguitar.app.TuxGuitar.startUIContext(TuxGuitar.java:154) at org.herac.tuxguitar.app.TuxGuitar.access$100(TuxGuitar.java:70) at org.herac.tuxguitar.app.TuxGuitar$1$1.run(TuxGuitar.java:131) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) java.lang.NullPointerException at org.herac.tuxguitar.app.view.component.table.TGTableHeaderMeasures.paintControl(TGTableHeaderMeasures.java:120) at org.herac.tuxguitar.app.view.util.TGBufferedPainterLocked.fillPaintBuffer(TGBufferedPainterLocked.java:52) at org.herac.tuxguitar.app.view.util.TGBufferedPainterLocked.paintBufferLocked(TGBufferedPainterLocked.java:61) at org.herac.tuxguitar.app.view.util.TGBufferedPainterListenerLocked.onPaint(TGBufferedPainterListenerLocked.java:14) at org.herac.tuxguitar.ui.event.UIPaintListenerManager.onPaint(UIPaintListenerManager.java:33) at org.herac.tuxguitar.ui.swt.event.SWTPaintListenerManager.paintControl(SWTPaintListenerManager.java:20) at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:234) at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89) at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4173) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1057) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1081) at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066) at org.eclipse.swt.widgets.Composite.WM_PAINT(Composite.java:1563) at org.eclipse.swt.widgets.Control.windowProc(Control.java:4818) at org.eclipse.swt.widgets.Display.windowProc(Display.java:4820) at org.eclipse.swt.internal.win32.OS.UpdateWindow(Native Method) at org.eclipse.swt.widgets.Decorations.setVisible(Decorations.java:1312) at org.eclipse.swt.widgets.Shell.setVisible(Shell.java:1958) at org.eclipse.swt.widgets.Shell.open(Shell.java:1267) at org.herac.tuxguitar.ui.swt.widget.SWTWindow.open(SWTWindow.java:70) at org.herac.tuxguitar.app.view.main.TGWindow.open(TGWindow.java:51) at org.herac.tuxguitar.app.TuxGuitar.startUIContext(TuxGuitar.java:154) at org.herac.tuxguitar.app.TuxGuitar.access$100(TuxGuitar.java:70) at org.herac.tuxguitar.app.TuxGuitar$1$1.run(TuxGuitar.java:131) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.action.TGActionManager.doPostExecution(TGActionManager.java:97) at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:69) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction.executeInterceptedAction(TGSyncThreadAction.java:37) at org.herac.tuxguitar.app.action.listener.lock.TGLockableActionListener.executeInterceptedAction(TGLockableActionListener.java:90) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction$1.run(TGSyncThreadAction.java:29) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) Caused by: org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.editor.TGEditorManager.doUpdateMeasures(TGEditorManager.java:173) at org.herac.tuxguitar.editor.TGEditorManager.access$200(TGEditorManager.java:19) at org.herac.tuxguitar.editor.TGEditorManager$5.run(TGEditorManager.java:91) at org.herac.tuxguitar.editor.TGEditorManager.runLocked(TGEditorManager.java:209) at org.herac.tuxguitar.editor.TGEditorManager.updateMeasures(TGEditorManager.java:89) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.applyUpdateMeasures(TGUpdateBuffer.java:73) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.apply(TGUpdateBuffer.java:44) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:53) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:69) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processEvent(TGUpdateListener.java:77) at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:24) ... 17 more Caused by: java.lang.NullPointerException at org.herac.tuxguitar.song.managers.TGSongManager.getTrack(TGSongManager.java:366) at org.herac.tuxguitar.app.view.component.tab.Caret.findTrack(Caret.java:103) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:77) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:72) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:64) at org.herac.tuxguitar.app.view.component.tab.Tablature.updateMeasures(Tablature.java:71) at org.herac.tuxguitar.app.view.component.tab.TablatureEditor.processUpdateEvent(TablatureEditor.java:58) at org.herac.tuxguitar.app.view.component.tab.TablatureEditor.processEvent(TablatureEditor.java:69) at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:24) ... 29 more org.herac.tuxguitar.action.TGActionException at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:79) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction.executeInterceptedAction(TGSyncThreadAction.java:37) at org.herac.tuxguitar.app.action.listener.lock.TGLockableActionListener.executeInterceptedAction(TGLockableActionListener.java:90) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction$1.run(TGSyncThreadAction.java:29) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) Caused by: org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.action.TGActionManager.doPostExecution(TGActionManager.java:97) at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:69) ... 14 more Caused by: org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.editor.TGEditorManager.doUpdateMeasures(TGEditorManager.java:173) at org.herac.tuxguitar.editor.TGEditorManager.access$200(TGEditorManager.java:19) at org.herac.tuxguitar.editor.TGEditorManager$5.run(TGEditorManager.java:91) at org.herac.tuxguitar.editor.TGEditorManager.runLocked(TGEditorManager.java:209) at org.herac.tuxguitar.editor.TGEditorManager.updateMeasures(TGEditorManager.java:89) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.applyUpdateMeasures(TGUpdateBuffer.java:73) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.apply(TGUpdateBuffer.java:44) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:53) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:69) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processEvent(TGUpdateListener.java:77) at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:24) ... 17 more Caused by: java.lang.NullPointerException at org.herac.tuxguitar.song.managers.TGSongManager.getTrack(TGSongManager.java:366) at org.herac.tuxguitar.app.view.component.tab.Caret.findTrack(Caret.java:103) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:77) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:72) at org.herac.tuxguitar.app.view.component.tab.Caret.update(Caret.java:64) at org.herac.tuxguitar.app.view.component.tab.Tablature.updateMeasures(Tablature.java:71) at org.herac.tuxguitar.app.view.component.tab.TablatureEditor.processUpdateEvent(TablatureEditor.java:58) at org.herac.tuxguitar.app.view.component.tab.TablatureEditor.processEvent(TablatureEditor.java:69) at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:24) ... 29 more java.lang.NullPointerException at org.herac.tuxguitar.app.view.toolbar.main.TGMainToolBarSectionTransport.updateTempoMap(TGMainToolBarSectionTransport.java:197) at org.herac.tuxguitar.app.view.util.TGSyncProcessLocked.processRunnable(TGSyncProcessLocked.java:30) at org.herac.tuxguitar.app.view.util.TGSyncProcessLocked.access$100(TGSyncProcessLocked.java:9) at org.herac.tuxguitar.app.view.util.TGSyncProcessLocked$1.run(TGSyncProcessLocked.java:39) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.action.TGActionManager.doPostExecution(TGActionManager.java:97) at org.herac.tuxguitar.action.TGActionManager.execute(TGActionManager.java:69) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction.executeInterceptedAction(TGSyncThreadAction.java:37) at org.herac.tuxguitar.app.action.listener.lock.TGLockableActionListener.executeInterceptedAction(TGLockableActionListener.java:90) at org.herac.tuxguitar.app.action.listener.thread.TGSyncThreadAction$1.run(TGSyncThreadAction.java:29) at org.herac.tuxguitar.app.synchronizer.TGSynchronizerControllerImpl$1$1.run(TGSynchronizerControllerImpl.java:29) at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40) at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185) at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3961) at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3588) at org.herac.tuxguitar.ui.swt.SWTApplication.start(SWTApplication.java:68) at org.herac.tuxguitar.app.TuxGuitar.createUIContext(TuxGuitar.java:124) at org.herac.tuxguitar.app.TuxGuitar.createApplication(TuxGuitar.java:109) at org.herac.tuxguitar.app.TGMainSingleton.launchTuxGuitar(TGMainSingleton.java:59) at org.herac.tuxguitar.app.TGMainSingleton.launchSingleton(TGMainSingleton.java:47) at org.herac.tuxguitar.app.TGMainSingleton.main(TGMainSingleton.java:35) Caused by: org.herac.tuxguitar.event.TGEventException at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:27) at org.herac.tuxguitar.event.TGEventManager.fireEvent(TGEventManager.java:42) at org.herac.tuxguitar.editor.TGEditorManager.doUpdateMeasures(TGEditorManager.java:173) at org.herac.tuxguitar.editor.TGEditorManager.access$200(TGEditorManager.java:19) at org.herac.tuxguitar.editor.TGEditorManager$5.run(TGEditorManager.java:91) at org.herac.tuxguitar.editor.TGEditorManager.runLocked(TGEditorManager.java:209) at org.herac.tuxguitar.editor.TGEditorManager.updateMeasures(TGEditorManager.java:89) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.applyUpdateMeasures(TGUpdateBuffer.java:73) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateBuffer.apply(TGUpdateBuffer.java:44) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:53) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processPostExecution(TGUpdateListener.java:69) at org.herac.tuxguitar.app.action.listener.cache.TGUpdateListener.processEvent(TGUpdateListener.java:77) at org.herac.tuxguitar.event.TGEventHandler.processEvent(TGEventHandler.java:24) ... 17 more

**Comment by helge17** [comment]
In https://github.com/helge17/tuxguitar/releases you can find my builds for Linux, FreeBSD, Windows and MacOS. The Windows builds include Java from https://portableapps.com/apps/utilities/OpenJDK . The builds bring some warnings on startup, but they start.

**Comment by HdCadUser** [comment]
> In https://github.com/helge17/tuxguitar/releases you can find my builds for Linux, FreeBSD, Windows and MacOS. The Windows builds include Java from https://portableapps.com/apps/utilities/OpenJDK . The builds bring some warnings on startup, but they start.

SHIT MAN, YOU ARE A MONSTER!!!

I've been trying to compile windows package for like a month if not two... And finally I found working app thanks to you. Love you man!!!

**Comment by helge17** [comment]
If someone is interested I can add my build script to my repository. Of course the script heavily depends on my build environment, and it needs some cleanup before I can publish it. The script builds TuxGuitar 2.x for all platforms: Linux, FreeBSD, Windows, MacOS and, in theory, also for Android.

**Comment by pterodactylus42** [comment]
Thanks so much for your builds helge :-) won't investigate further in redmond.

**Comment by pterodactylus42** [comment]
fixed
