### ISSUE TITLE
Maven fails

### ISSUE THREAD

**Issue by dmitsuki** [pterodactylus42/tuxguitar#2]
Maven fails to find dependencies. This is noted in the readme, but I have no clue how to actually use anything on that webpage to fix said dependencies on Linux. Any guidance to that would be greatly appreciated.

**Comment by ohli** [comment]
Hi @dmitsuki ,

although your error description is very vague (next time, provide logs), I assume you have trouble with getting SWT to work properly.

So here is how I solved it under Arch Linux:

```
# download SWT
wget -qO- https://archive.eclipse.org/eclipse/downloads/drops4/R-4.13-201909161045/download.php?dropFile=swt-4.13-gtk-linux-x86_64.zip | unzip

cd <where tuxguitar is>/build-scripts/tuxguitar-linux-x86_64

mvn install:install-file -Dfile=<absolute path to your swt download>/swt-4.13-gtk-linux-x86_64/swt.jar -DartifactId=org.eclipse.swt.gtk.linux.x86_64 -Dpackaging=jar -DgroupId=org.eclipse.swt -Dversion=4.13

# now you can build tuxguitar without errors
mvn -P native-modules package

**Comment by dmitsuki** [comment]
Thanks. I didn't include logs because the exact issue was noted in the readme. Perhaps you could include what you posted here in the readme? I think that would be helpful. And thanks again for the help.

**Comment by ohli** [comment]
@pterodactylus42 Maybe just link this issue in the INSTALLATION.md?

Working on a PKGBUILD for Arch Linux btw ;-)

**Comment by pterodactylus42** [comment]
Good point. Done :-)
