### ISSUE TITLE
Download of swt no longer works as expected

### ISSUE THREAD

**Issue by XaverStiensmeier** [pterodactylus42/tuxguitar#5]
In the readme `wget -qO- https://archive.eclipse.org/eclipse/downloads/drops4/R-4.13-201909161045/download.php?dropFile=swt-4.13-gtk-linux-x86_64.zip | unzip` is suggested, but wget just returns html code explaining that if the download doesn't start one needs to press the link. By downloading it manually and adapting the path in the maven command `mvn install:install-file -Dfile=$PATH_TO_DOWNLOAD_FOLDER/swt-4.13-gtk-linux-x86_64/swt.jar -DartifactId=org.eclipse.swt.gtk.linux.x86_64 -Dpackaging=jar -DgroupId=org.eclipse.swt -Dversion=4.13` one can work around this.

**Comment by ohli** [comment]
You are right @XaverStiensmeier , the Download URL mentioned in #2 changed (and `unzip` is not reliable with multiple files from stdin)

This would be the corrected oneliner:

```
wget -qO- "https://www.eclipse.org/downloads/download.php?file=/eclipse/downloads/drops4/R-4.13-201909161045/swt-4.13-gtk-linux-x86_64.zip" | bsdtar -xf -
````

@pterodactylus42 you may adapt the README again

...and I try the AUR package once more.

**Comment by pterodactylus42** [comment]
INSTALL.md is up to date again...
